name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk --debug

      - name: Debug SonarCloud Token
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "ERROR: SONAR_TOKEN is not set"
            exit 1
          else
            echo "SONAR_TOKEN is set"
          fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io'
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=your-project-key
            -Dsonar.organization=your-organization-key
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=lib
            -Dsonar.test.sources=test
            -Dsonar.verbose=true
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
